### PR TITLE
DNA-RNA hybrid model

### PR DESCRIPTION
**Pull request by eryykr**

### CODE REVIEW

**Comment by ErikPoppleton** [comment]
Excited to see this update!  It looks like you've got a bunch of test files in `analysis/test`.  There is a script in there called `cleanup.sh` which will remove all the generated files to clean up the commit.  Can you please run that to remove the files?

**Comment by eryykr** [comment]
Sure, just did it!

**Comment by lorenzo-rovigatti** [comment]
Thanks for the PR, this will be a great addition to the code! I'm trying to make sense of the changes so that I can make sure that we are not going to break anything. In the meantime, can you resolve `MCBackend.cpp`'s conflict? I have the impression that you didn't make any changes to the file yourself, but it's just a bit outdated with respect to the master one.

**Comment by lorenzo-rovigatti** [comment]
Sorry for the multiple messages. The other issue I see is that you are trying to merge with master a branch that was merged with new_topology. I think we need to first merge that into master, and then we can go ahead with this one.

**Comment by lorenzo-rovigatti** [comment]
Erik and I are working on the new topology branch. We plan to merge it later this week and then I'll start working on this one. However, since there are some core files that are involved, I think it would be better if we could merge your code into a non-master branch. I don't know if you can change that after you created the PR or you have to make a new one. If you can't edit this one then I'll close it and you can make a new one.

**Comment by eryykr** [comment]
Looks like this can be easily done - I've now changed the base branch of
the PR to the new topology one.

**Comment by lorenzo-rovigatti** [comment]
@eryykr thanks again for the PR! I have merged it into a separate branch and will work on merging it to master as soon as I'm done with `oat_dev`.

**Pull request merged**
