### PR TITLE
Small update to gpu compiler flags to support compute capabilities 8.0 and 8.6 as well.

### PR DESCRIPTION
**Pull request by Subhajit-Roy-Partho**
This adds compiler flags for Ampere gpu with compute capabilities 8.0 and 8.6 as provided in https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/select_compute_arch.cmake.

### CODE REVIEW

**Comment by lorenzo-rovigatti** [comment]
Thanks! Those are some extensive changes. Did you change the file yourself or you used some other file (e.g. by NVIDIA) as template?

**Comment by Subhajit-Roy-Partho** [comment]
Apologies for my delayed reply. It is mostly copied from the FindCUDA module of the CMAKE github and as given by nvidia cuda documentation. I didn't write it. I tried it out on our A100 gpu which are with compute capabilities 8.0. On average it only speed up by 1.01 using the above code.

**Comment by lorenzo-rovigatti** [comment]
Some of the changes I don't understand. Does it work on older architectures as well?

**Comment by Subhajit-Roy-Partho** [comment]
The oldest GPU I have access to is GTX1080 and it works on it. But not sure about even older gpus.

**Pull request merged**
